# Generated by Django 4.2.30 on 2026-07-16 17:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('generated_by', models.CharField(default='GPT', max_length=100)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('Insurance Expiry', 'Insurance Expiry'), ('License Expiry', 'License Expiry'), ('Maintenance Due', 'Maintenance Due'), ('Trip Started', 'Trip Started'), ('Trip Completed', 'Trip Completed'), ('Fuel Alert', 'Fuel Alert'), ('AI Alert', 'AI Alert'), ('AI Recommendation', 'AI Recommendation')], max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
