# Generated by Django 4.2.30 on 2026-07-30 18:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_rental_iq_mvp'),
        ('operators', '0001_rental_iq_mvp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_id', models.CharField(max_length=32, unique=True)),
                ('manufacturer', models.CharField(default='Caterpillar', max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('gross_power_kw', models.FloatField(blank=True, null=True)),
                ('operating_weight_kg', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equipment_models',
                'ordering': ['model_id'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.CharField(max_length=32, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('manufacture_year', models.IntegerField(blank=True, null=True)),
                ('acquisition_type', models.CharField(blank=True, max_length=50)),
                ('current_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ACTIVE', 'Active'), ('IDLE', 'Idle'), ('MAINTENANCE', 'Maintenance'), ('RETIRED', 'Retired')], default='AVAILABLE', max_length=32)),
                ('total_engine_hours', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='operators.operator')),
                ('current_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='sites.site')),
                ('model_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='equipment.equipmentmodel')),
            ],
            options={
                'db_table': 'equipment_assets',
                'ordering': ['asset_id'],
            },
        ),
    ]
