# Generated by Django 4.2.30 on 2026-07-16 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_expiry', models.DateField()),
                ('address', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=50)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('joining_date', models.DateField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On Trip', 'On Trip'), ('On Leave', 'On Leave'), ('Inactive', 'Inactive')], default='Available', max_length=20)),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_drivers', to='vehicles.vehicle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'drivers',
                'indexes': [models.Index(fields=['license_number'], name='drivers_license_29348f_idx')],
            },
        ),
    ]
