# Generated by Django 4.2.30 on 2026-07-16 17:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mechanic_name', models.CharField(max_length=255)),
                ('service_type', models.CharField(max_length=100)),
                ('service_date', models.DateField()),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('repair_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'maintenance',
                'indexes': [models.Index(fields=['vehicle'], name='maintenance_vehicle_fe0481_idx')],
            },
        ),
    ]
