# Generated by Django 4.2.30 on 2026-07-30 18:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_rental_iq_mvp'),
        ('sites', '0001_rental_iq_mvp'),
        ('operators', '0001_rental_iq_mvp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rental_id', models.CharField(max_length=32, unique=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('rental_days', models.IntegerField(default=0)),
                ('daily_rate', models.FloatField(default=0)),
                ('rental_status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='equipment.equipment')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentals', to='operators.operator')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentals', to='sites.site')),
            ],
            options={
                'db_table': 'rentals',
                'ordering': ['-check_out_date'],
            },
        ),
    ]
