# Generated by Django 4.2.30 on 2026-07-16 17:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('distance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('trip_status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Started', 'Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='drivers.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'trips',
                'indexes': [models.Index(fields=['vehicle'], name='trips_vehicle_42da11_idx'), models.Index(fields=['driver'], name='trips_driver__721cfc_idx'), models.Index(fields=['trip_status'], name='trips_trip_st_b6ef66_idx')],
            },
        ),
    ]
