# Generated by Django 4.2.30 on 2026-07-16 17:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        ('vehicles', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('speed', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('heading', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.driver')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'vehicle_locations',
                'indexes': [models.Index(fields=['vehicle'], name='vehicle_loc_vehicle_f2a1cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='GPSHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('speed', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_history', to='trips.trip')),
            ],
            options={
                'db_table': 'gps_history',
                'indexes': [models.Index(fields=['trip'], name='gps_history_trip_id_ad058e_idx')],
            },
        ),
    ]
