# Generated by Django 4.2.30 on 2026-07-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletelemetry',
            name='source',
            field=models.CharField(choices=[('SIMULATOR', 'Simulator'), ('MOBILE', 'Mobile'), ('GPS_DEVICE', 'GPS Device'), ('IOT_GATEWAY', 'IoT Gateway'), ('DATASET', 'Dataset')], default='SIMULATOR', max_length=30),
        ),
    ]
