# Generated by Django 4.2.30 on 2026-07-30 18:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_id', models.CharField(max_length=32, unique=True)),
                ('site_name', models.CharField(max_length=255)),
                ('site_type', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=32)),
            ],
            options={
                'db_table': 'rental_sites',
                'ordering': ['site_id'],
            },
        ),
    ]
