# Generated by Django 4.2.30 on 2026-07-16 17:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fuel_station', models.CharField(blank=True, max_length=255)),
                ('fuel_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mileage', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fuel_date', models.DateField()),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_logs', to='drivers.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'fuel_logs',
                'indexes': [models.Index(fields=['vehicle'], name='fuel_logs_vehicle_f19993_idx')],
            },
        ),
    ]
