# Generated by Django 4.2.30 on 2026-07-30 18:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operator_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('certification', models.CharField(blank=True, max_length=100)),
                ('experience_years', models.IntegerField(default=0)),
                ('shift', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(default='ACTIVE', max_length=32)),
            ],
            options={
                'db_table': 'rental_operators',
                'ordering': ['operator_id'],
            },
        ),
    ]
